# Generated by Django 5.0.1 on 2024-02-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products_image_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='motto',
            field=models.TextField(default='Get Your Greatest Fit'),
        ),
    ]
